success_rate_check_Bispectrum
success_rate_check_Bispectrum_sampling
success_rate_check_Bispectrum_spectra_mat
success_rate_check_Trispectrum
success_rate_check_Trispectrum_sampling
success_rate_check_Trispectrum_sampling